site_name: P5R PC Essentials Documentation
site_url: https://sewer56.dev/p5rpc.modloader

repo_name: Sewer56/p5rpc.modloader
repo_url: https://github.com/Sewer56/p5rpc.modloader

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: slate
    
nav:
  - Home: index.md
  - Usage: usage.md
  - Extensions:
    - PAK Emulator: pak.md